language: node_js
node_js:
- stable
- '6'
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: u8+OP7KMkGLgmb6PIzBCOMuahCVt7G89C3w8b+MHEOxn2KWfd6fsrbiDYJBylzfGcSnyBEIlLtPxHyPRCVkSd/pvQ1bW+njywX+Dc+N9cfijsLetEcaVBILpFPZzxwvDQyPcIYgITviXAih2BxetsNogh9Zh13jJZAFKuiDuh0ZONim6sHJTfBvlHsi/b1uwuS2y2d/RVD52aKqowm/rO7zIS+Tmna9ymY7M7CrVnfQbbAhD5RxpQPBljO8oPlUUJbngn3b4PPmzw79u74SVzBcQsJaP2+xd2SSDvqVOAMPxkwHcQzMhjtU7F3oNkvgi9b/rqYsJpdu2h498NiAm3J5UWweDeu2a9SB24pGRqJ+pkj3AjmlmtJQSbLIe2SiV8m/tBlFDgGTuObCHAIGsDwkiduqX9KdaOBG0Kdk+D+0Sc62XvkhFbZx0Rp+2U6vi0tK/U0rtjh2qHYa3/htzh904zQ26NVCZ+9mlp0kRATm8inl1lHuDoROiW7Jvz4PW1fbcarVq6DpgGxmrLvonjhwXxes6s9BiUxey5KBASlcA3ifasWT0hVPc88pLpXj85cbFo/pchpRG7y4gQcMy/w6RpiIyVnT4X091YP5VflRb9TSt+NszDebPWlZ1hFy2jo2HrjYJAg6ki3Vt0Oj8SrefRn57SfdsZPs5ddAaWvY=
  app: protected-peak-77282